#!/bin/sh

set -e

case "$(uname -m)" in
    arm*)
        cp /data/www/localhost/busybox_armhf /data/www/localhost/busybox
        ;;
    x86_64)
        cp /data/www/localhost/busybox_x86_64 /data/www/localhost/busybox
        ;;
    *)
        echo "No compatible busybox binary for this architecture." 1>&2
        exit 1
        ;;
esac

exit 0
